name: flutter_responsive_breakpoints
description: This package provides breakpoints to help achieve responsive designs.
version: 0.0.2
homepage: https://github.com/florian-lefebvre/flutter_responsive_breakpoints

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
